# Generated by Django 4.2.18 on 2025-02-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='creation_time',
        ),
    ]
